version: "1.0"
info:
  model: int-scaffold
packages:
- name: Serengeti_GH_1912Project
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
- name: upperfspackage
  version: "1.0"
  gitServerName: srcCtrl_shared_bitbucket_Arti
  gitUrl: https://bitbucket.org/testartiibm
  gitUsername: artikhare
  gitBranch: master
services:
- serviceName: project.serengeti_gh_1912.integrations:bitbucketfs
  packages:
  - name: Serengeti_GH_1912Project
    version: "1.0"
  - name: upperfspackage
    version: "1.0"
- serviceName: UpperFSPackage:upperfs
  packages:
  - name: upperfspackage
    version: "1.0"
- serviceName: pub.string:toUpper
  packages:
  - name: WmPublic
    version: 11.1.0.0.2099
configurationVariables:
  jdbc.SAP TxStore Pool.maxConns: "10"
  jdbcfunc.SAPTxStore.failFastMode: false
  jdbc.SAP TxStore Pool.poolThreshold: "0"
  jdbc.jdbcTestPool.snoopparms: ddtdbg.ProtocolTraceEnable=true;ddtdbg.ProtocolTraceMaxline=16;ddtdbg.ProtocolTraceLocation=logs/snoop/jdbcTestPool.log;ddtdbg.ProtocolTraceShowTime=true
  jdbc.SAP TxStore Pool.spyenabled: "false"
  jdbc.jdbcTestPool.maxConns: "10"
  jdbc.jdbcTestPool.userid: root
  jdbc.SAP TxStore Pool.useSSL: "false"
  jdbc.SAP TxStore Pool.password: "{AES}nrGf3u7Wt20hFBGh5ZeEuQ=="
  jdbc.jdbcTestPool.spyenabled: "false"
  jdbc.SAP TxStore Pool.spyparms: SpyAttributes=(log=(file)logs/spy/SAP_TxStore_Pool.log;logTName=yes;timestamp=yes)
  jdbc.jdbcTestPool.snoopenabled: "false"
  jdbc.SAP TxStore Pool.snoopenabled: "false"
  jdbc.jdbcTestPool.spyparms: SpyAttributes=(log=(file)logs/spy/jdbcTestPool.log;logTName=yes;timestamp=yes)
  jdbc.SAP TxStore Pool.expireTime: "60000"
  jdbc.SAP TxStore Pool.minConns: "5"
  jdbc.SAP TxStore Pool.driverAlias: MySQL CC Driver
  jdbcfunc.SAPTxStore.connPoolAlias: SAP TxStore Pool
  jdbc.jdbcTestPool.waitingThread: "0"
  jdbc.jdbcTestPool.minConns: "0"
  jdbc.jdbcTestPool.expireTime: "60000"
  jdbc.SAP TxStore Pool.dbURL: jdbc:mysql://localhost:3306/SAPTRANSACTIONSTORE?useSSL=false&characterEncoding=utf-8&autoReconnect=true&maxReconnects=5&sessionVariables=wait_timeout=2147483
  jdbc.SAP TxStore Pool.waitingThread: "10"
  jdbc.SAP TxStore Pool.description: Connection Pool for the SAP Transaction Store
  jdbc.jdbcTestPool.driverAlias: MySQL Database Java Connector Driver
  jdbc.SAP TxStore Pool.snoopparms: ddtdbg.ProtocolTraceEnable=true;ddtdbg.ProtocolTraceMaxline=16;ddtdbg.ProtocolTraceLocation=logs/snoop/SAP_TxStore_Pool.log;ddtdbg.ProtocolTraceShowTime=true
  jdbc.jdbcTestPool.password: "{AES}er+I3U8nDVm8F4DBRST1+A=="
  jdbc.jdbcTestPool.dbURL: jdbc:mysql://mysql.test.local:3306/webm
  jdbc.jdbcTestPool.poolThreshold: "0"
  jdbc.SAP TxStore Pool.userid: root
  jdbc.jdbcTestPool.useSSL: "false"
